### ISSUE TITLE
missing git tags

### ISSUE THREAD

**Issue by tampakrap** [voxpupuli/hiera-eyaml-gpg#32]
Could we please have git tags for the already released versions?

**Comment by alexjfisher** [comment]
@tampakrap This project has recently been migrated to Vox Pupuli and I've looked into creating these, but unfortunately, it doesn't look like it'll be possible.  There are releases on rubygems that just don't have commits.

For example, on rubygems, there is a 0.7-rc1.  Downloading this gem and 0.6 then diffing...
```diff
diff -Naur 0.6/lib/hiera/backend/eyaml/encryptors/gpg/version.rb 0.7.rc1/lib/hiera/backend/eyaml/encryptors/gpg/version.rb
--- 0.6/lib/hiera/backend/eyaml/encryptors/gpg/version.rb	1970-01-01 01:00:00.000000000 +0100
+++ 0.7.rc1/lib/hiera/backend/eyaml/encryptors/gpg/version.rb	2018-03-01 21:56:47.000000000 +0000
@@ -3,7 +3,7 @@
     module Eyaml
       module Encryptors
         module Gpg
-          VERSION = "0.6"
+          VERSION = "0.7.rc1"
         end
       end
     end
diff -Naur 0.6/lib/hiera/backend/eyaml/encryptors/gpg.rb 0.7.rc1/lib/hiera/backend/eyaml/encryptors/gpg.rb
--- 0.6/lib/hiera/backend/eyaml/encryptors/gpg.rb	1970-01-01 01:00:00.000000000 +0100
+++ 0.7.rc1/lib/hiera/backend/eyaml/encryptors/gpg.rb	2018-03-01 21:56:47.000000000 +0000
@@ -109,7 +109,7 @@
 
               unless recipient_file.nil?
                 recipient_file.readlines.map{ |line|
-                  line.strip unless line.start_with? '#'
+                  line.strip unless line.start_with? '#' or line.strip.empty?
                 }.compact
               else
                 []
```

This change has never been committed. https://github.com/voxpupuli/hiera-eyaml-gpg/blob/660a34f26e33aae4d4f520bc74b53c7fec294c03/lib/hiera/backend/eyaml/encryptors/gpg.rb#L113

Another example.
The commit that bumped the version to 0.6 https://github.com/voxpupuli/hiera-eyaml-gpg/commit/f610dbc46173d6b71bea5285961afce45e2ef992 was made over two years after a 0.6 release was uploaded to rubygems.

From this point forwards, travis will be responsible for uploading new releases to rubygems whenever we push a new tag.  Sorry it's not been possible to backfill the tags.
