### ISSUE TITLE
wrong version in version.rb

### ISSUE THREAD

**Issue by tampakrap** [voxpupuli/hiera-eyaml-gpg#33]
version.rb still says 0.5, it should be updated to 0.6 or maybe 0.7?

**Comment by tampakrap** [comment]
also, I just noticed this:

```
% eyaml version
[hiera-eyaml-core] Loaded config from /home/tampakrap/.eyaml/config.yaml
[hiera-eyaml-core] hiera-eyaml (core): 2.0.8
[hiera-eyaml-core] hiera-eyaml-gpg (gem): unknown (is plugin compatible with eyaml 2.0+ ?)
```

probably I should file a separate bug for this?

**Comment by alexjfisher** [comment]
As explained in https://github.com/voxpupuli/hiera-eyaml-gpg/issues/32, going forwards releases to rubygems will only be based on tags deployed by travis.
