### ISSUE TITLE
Does not work with Puppet 5.5.3

### ISSUE THREAD

**Issue by threepistons** [voxpupuli/hiera-eyaml-gpg#47]
- Given CentOS 7.5.1804 and Puppet 5.5.3 from the Puppetlabs Yum repo and hiera-eyaml-gpg 0.6 and ruby_gpg 0.3.2, both installed by the ```/opt/puppetlabs/server/bin/puppetserver gem install``` command.
- When I try to apply my manifests with ```puppet agent -t```
- I get ```Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Internal Server Error: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- hiera/backend/eyaml/encryptors/gpg```
- I expected that the GPG backend would have decrypted and applied my test manifest.

**Comment by alexjfisher** [comment]
Odd.
@threepistons Are you still unable to get it working?  I've personally used it on Centos 7 with puppet 5.5 and not experienced the problem you describe.

**Comment by threepistons** [comment]
> Odd.
> @threepistons Are you still unable to get it working? I've personally used it on Centos 7 with puppet 5.5 and not experienced the problem you describe.

@ghoneycutt's #50 gives me a clue as to why it doesn't.  Upgrading now...

**Comment by threepistons** [comment]
It's happy with 6.3.

**Comment by threepistons** [comment]
Resolved by #50, Puppet 5.5.3 officially declared to be too old for this module.

**Comment by alexjfisher** [comment]
@threepistons Whilst not something we officially support, I'm still surprised you didn't get it working with 5.5.3.  I can't think of any reason it wouldn't have done.  Glad you got it working with Puppet 6 though.
