### ISSUE TITLE
new release for GPG error output fix

### ISSUE THREAD

**Issue by lukebigum** [voxpupuli/hiera-eyaml-gpg#70]
Hello,

Can we get a new release that's got commit 2681e995ee in it please?  I keep getting weird GPG error messages in my password files :-)

-Luke

**Comment by alexjfisher** [comment]
Sounds reasonable. https://github.com/voxpupuli/hiera-eyaml-gpg/pull/71

**Comment by alexjfisher** [comment]
Enjoy! https://rubygems.org/gems/hiera-eyaml-gpg/versions/0.7.4
